### ISSUE TITLE
lack of a few mob heads?

### ISSUE THREAD

**Issue by J-F2** [Pedro270707/headed#5]
ive noticed the lack of the following:

- regular piglin head
- hoglin head
- zombified hoglin head

there may be more, but the regular piglin head, even though it is the same model for the other piglin heads, is not in the mod yet.

this isnt an issue per se, more of a question of when these would be added. thank you!

**Comment by Pedro270707** [comment]
Piglin heads are available in vanilla by enabling experimental features (1.19.2 and 1.18.2 did not have it so I added it in)
Hoglin and zoglin heads weren't adding due to being too big for a block. If I ever add them it'll be as a separate mod since I don't want any heads here to be rescaled just to fit in a square meter.

**Comment by J-F2** [comment]
> Piglin heads are available in vanilla by enabling experimental features (1.19.2 and 1.18.2 did not have it so I added it in) Hoglin and zoglin heads weren't adding due to being too big for a block. If I ever add them it'll be as a separate mod since I don't want any heads here to be rescaled just to fit in a square meter.

is there a technical reason that heads exceeding the size of a block cannot be added? if rotated, it could surely fit on the ground, or i could see it being limited to only being able to be mounted on a wall.

**Comment by Pedro270707** [comment]
There's no limitation, but I don't see it fitting on this mod as it's meant to be a vanilla+ and Mojang would probably not rescale a ghast head all the way down just to fit inside a block. I'm working hard to make the extension mod though so that players can still enjoy the heads which I don't see as fitting.
